version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 471112830639.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Build the Docker image...
      - docker build -t ecolab-frontend .
      - echo Tag the Docker image...
      - docker tag ecolab-frontend:latest 471112830639.dkr.ecr.us-east-1.amazonaws.com/ecolab-frontend:latest
  post_build:
    commands:
      - echo Push the Docker image to ECR...
      - docker push 471112830639.dkr.ecr.us-east-1.amazonaws.com/ecolab-frontend:latest